language: minimal

env:
  - NODE_VERSION=16.14.2 NAMESPACE=mkkhedawat IMAGE_VERSION=v1.0.0 TAG=$NAMESPACE/cypress-plus:$NODE_VERSION-$IMAGE_VERSION TAG_LATEST=$NAMESPACE/cypress-plus:latest  TAG_NODE_LATEST=$NAMESPACE/cypress-plus:$NODE_VERSION-latest 

services:
  - docker
  
script:
  - docker build -t $TAG .
  
after_script:
  - |
    if [ $TRAVIS_PULL_REQUEST == "false" ]; then
      echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin && \
      docker push $TAG && \
      docker tag $TAG $TAG_NODE_LATEST && \
      docker push $TAG_NODE_LATEST && \
      docker tag $TAG $TAG_LATEST && \
      docker push $TAG_LATEST;  \
    fi
    
branches:
  only:
    - master
